// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB5VMDPuSu-xKHOPXE6SwMtxvx_jaxA_4',
    appId: '1:1084844005739:web:4703257386dd298072142e',
    messagingSenderId: '1084844005739',
    projectId: 'protecin-producao',
    authDomain: 'protecin-producao.firebaseapp.com',
    storageBucket: 'protecin-producao.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6hVXpzsOvOcVJ8cNia2rZLnkju1YoSFk',
    appId: '1:1084844005739:android:375a46dde142e42f72142e',
    messagingSenderId: '1084844005739',
    projectId: 'protecin-producao',
    storageBucket: 'protecin-producao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS7STENqTkg4ereTfB5kLhW8iMf5zYuoU',
    appId: '1:1084844005739:ios:ddcf4c650b61412b72142e',
    messagingSenderId: '1084844005739',
    projectId: 'protecin-producao',
    storageBucket: 'protecin-producao.firebasestorage.app',
    iosBundleId: 'com.example.protecinProducao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS7STENqTkg4ereTfB5kLhW8iMf5zYuoU',
    appId: '1:1084844005739:ios:ddcf4c650b61412b72142e',
    messagingSenderId: '1084844005739',
    projectId: 'protecin-producao',
    storageBucket: 'protecin-producao.firebasestorage.app',
    iosBundleId: 'com.example.protecinProducao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB5VMDPuSu-xKHOPXE6SwMtxvx_jaxA_4',
    appId: '1:1084844005739:web:d31f2a515136a82f72142e',
    messagingSenderId: '1084844005739',
    projectId: 'protecin-producao',
    authDomain: 'protecin-producao.firebaseapp.com',
    storageBucket: 'protecin-producao.firebasestorage.app',
  );

}